### ISSUE TITLE
questionable cluster selection in multi cluster setup

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-vsphere-cpi-release#113]
it was reported that given two clusters (one is much smaller than the other), smaller cluster was being picked for no apparent reason. let's understand this behavior in the context of that env and also argument the cpi with extensive logging about decisions it's making and reasons behind them.

**Comment by EleanorRigby** [comment]
#35 : This issue was earlier seen in cpi release 45.0.1. which was fixed in v46+ .

The culprit here was mis-calculation of balance score (an indicator of free space with cluster)

Adding more logging is being worked on.
