### ISSUE TITLE
vSphere CPI doesn't escape network port groups correctly

### ISSUE THREAD

**Issue by z4ce** [cloudfoundry-incubator/bosh-vsphere-cpi-release#114]
Running `create-env -o bosh-deployment/vsphere/cpi.yml -v network_name='dvPortGroup-10.60.30.0/24-PCF-MGMT'`

results in:
```
CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Unable to find network 'dvPortGroup-10.60.30.0/24-PCF-MGMT'. Verify that the portgroup exists.","ok_to_retry":false}
```

Work around is to specify using `%2f` in place of the slash like: `create-env -o bosh-deployment/vsphere/cpi.yml -v network_name='dvPortGroup-10.60.30.0%2f24-PCF-MGMT'`

**Comment by ktchen14** [comment]
Unfortunately the `/` character in a network name is used by the BOSH CPI to allow a user to refer to a distributed portgroup nested within a distributed switch or a distributed portgroup nested under a network folder. At the moment this is more or less the intended behavior.

**Comment by cppforlife** [comment]
i think you can use `%2F` (`%2f`) instead of slash.

**Comment by cppforlife** [comment]
oops didnt see your comment ending... doh. @ktchen14 i wonder if it's worth adding this to some doc somewhere?

**Comment by cppforlife** [comment]
related: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/119

**Comment by yeshwantbabar** [comment]
Opening a doc PR for this.
