### ISSUE TITLE
Question: does the CPI support use of a NAT'd IP address for jumpbox/director provisioning

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [cloudfoundry-incubator/bosh-vsphere-cpi-release#115]
The documentation here states that it is possible to supply an external IP for vsphere:

https://bosh.io/docs/init-external-ip/

In a NAT'd network, the jumpbox (cppforlife/jumpbox-deployment) or director is brought up with the CPI method create-vm. The cli then attempts to connect to the VM using the internal_ip for the VM. If the VM on a NAT'd vlan, the cli cannot connect to the VM. Is it possible to have the cli check for the VM on an 'external' ip address for the jumpbox or director?

**Comment by antitux** [comment]
I have a similar environment and ended up creating an .envrc function to get around this:
```
export SSH_KEY="$(bosh int ./creds.yml --path /jumpbox_ssh/private_key)"
export GW_HOST="$(bosh int ./creds.yml --path /jumpbox_host)"

ssh-add -D
ssh-add - <<< "$SSH_KEY"

bosh() {
  case $* in
    ssh* )
      shift 1
      command bosh ssh --gw-user=jumpbox --gw-host=$GW_HOST "$@"
    ;;
    * )
      command bosh "$@"
    ;;
  esac
}```

**Comment by jaresty** [comment]
@patrick-huber-pivotal I don't believe you can do this natively with the bosh-cli; we work around this limitation in our CI by setting up an ssh tunnel as you can see [here](https://github.com/pivotal-cf/bosh-concourse-deployments/blob/master/ci/utils#L117-L129) to do create-env through a jumpbox.  After that, you should be able to use BOSH_ALL_PROXY to target and use the director.

**Comment by patrick-huber-pivotal** [comment]
Ok, thanks for the info. I'll close out for now and work on testing this.
