### ISSUE TITLE
[feature-request] NSX-T CPI: Support for client certificate based authentication

### ISSUE THREAD

**Issue by shyaamsn** [cloudfoundry-incubator/bosh-vsphere-cpi-release#118]
Currently, NSX-T CPI supports username/password for authentication. This is a feature request to also support client certificate based authentitcation

**Comment by EleanorRigby** [comment]
@medvedzver

**Comment by medvedzver** [comment]
@EleanorRigby A little different from what I was looking into.

@shyaamsn Just to make sure - do you want to use [this](https://pubs.vmware.com/vidm/index.jsp?topic=%2Fcom.vmware.wsair-administration%2FGUID-26C15BA2-3B76-4E53-ABBB-E83271F1B9CB.html) NSX-t feature and instead of NSXt password/login you want to provide NSXt cert for CPI configuration. Am I right?

**Comment by shyaamsn** [comment]
@medvedzver Yes instead of username/password based login I want to provide a certificate and key for authentication.

But its not through identity manager. Unfortunately, there isnt much documentation about this. 

But this is how it works:
1. Create a certificate and key (using openssl)
2. Import the certificate in nsx manager
3. Create a principal identity (e.g. vsphere-cpi) binding with the certificate
4. Issue requests to NSX-T using certificate and key and any object created would be associated with principal identity

https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-7DF34C3B-6684-4EA9-9CE9-FAF7490A7637.html

https://docs.vmware.com/en/VMware-NSX-T/2.2/com.vmware.nsxt.admin.doc/GUID-BC3BA708-1A79-4741-BF16-968C74565E39.html

**Comment by nehagjain15** [comment]
@shyaamsn This has been added as part of this [PR] (https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/pull/123)

**Comment by EleanorRigby** [comment]
Delivered in v51.
