### ISSUE TITLE
Assets for NSX blog post

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/bosh-vsphere-cpi-release#12]
<img width="743" alt="load_balancer_enabled_final" src="https://cloud.githubusercontent.com/assets/1923644/19787469/c8cbaf3a-9c57-11e6-9da4-5b06016dfa3f.png">

**Comment by ljfranklin** [comment]
<img width="597" alt="nsx-application-profile" src="https://cloud.githubusercontent.com/assets/1923644/19787709/18ca64b2-9c59-11e6-9cb9-c2c3660eae9c.png">

**Comment by ljfranklin** [comment]
<img width="554" alt="nsx_pool" src="https://cloud.githubusercontent.com/assets/1923644/19788122/7da964c6-9c5b-11e6-8fd8-cd14d63a9876.png">

<img width="609" alt="nsx_virtual_server_final" src="https://cloud.githubusercontent.com/assets/1923644/19788285/3efaa0b8-9c5c-11e6-95c9-94a9b9f6ce6c.png">

**Comment by cunnie** [comment]
<img width="647" alt="add_deny-ssh" src="https://cloud.githubusercontent.com/assets/1020675/19875589/1143050c-9f8b-11e6-8955-9ecbe39112c3.png">

**Comment by cunnie** [comment]
<img width="647" alt="add_deny-ssh" src="https://cloud.githubusercontent.com/assets/1020675/19894256/8ae8be82-a009-11e6-9b2b-6a66f45f5839.png">

<img width="581" alt="add_deny_ssh" src="https://cloud.githubusercontent.com/assets/1020675/19895148/db0e53ba-a00c-11e6-80c4-71dde83caeb2.png">
