### ISSUE TITLE
resize_disk method should fail as NotImplemented 

### ISSUE THREAD

**Issue by dpb587-pivotal** [cloudfoundry-incubator/bosh-vsphere-cpi-release#127]
When director has `director.enable_cpi_resize_disk` enabled and using the vSphere CPI, disk size changes are ignored and the original disk size is always used.

More context if helpful... the `resize_disk` method was introduced a while ago as an optimization to allow disk resizing from the IaaS level. From director, this is feature flagged with [`director.enable_cpi_resize_disk`](https://github.com/cloudfoundry/bosh/blob/d4825952d4cf6de4bc7bb4f0bf1ef864987074e1/jobs/director/spec#L112) and currently disabled by default. To make this call backwards-compatible across CPIs, director optimistically calls `resize_disk`, but if the call fails with `NotImplemented ` or `NotSupported` ([source](https://github.com/cloudfoundry/bosh/blob/7da33234c7aa3092a72a9d2c5c00c71c94c5b593/src/bosh-director/lib/bosh/director/disk_manager.rb#L245)), it falls back to the full create new disk + migrate workflow.

In this case, it looks like the CPI's [`resize_disk`](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/dfe878579cbab768af07a12bb5543cd016cbb762/src/vsphere_cpi/lib/cloud/vsphere/cloud.rb#L447-L449) method is a no-op which causes director to believe it was successful. I'd recommend implementing it, or, at least, raising `NotImplemented`/`NotSupported` for the time being to avoid disk size changes potentially being ignored.

Let us know if you have more questions. Thanks!

**Comment by nehagjain15** [comment]
@dpb587-pivotal Filed a story in tracker #[159212203](https://www.pivotaltracker.com/story/show/159212203)

**Comment by nehagjain15** [comment]
@dpb587-pivotal This was merged to master, so closing this bug

**Comment by dpb587-pivotal** [comment]
Thanks for the quick turnaround!

**Comment by dennisjbell** [comment]
The README still says Native Disk Resize is Not Supported.  Are there further issues that are preventing this from being supported, or was that just missed?
