### ISSUE TITLE
Confusion on address/host property in manifest vs CPI config

### ISSUE THREAD

**Issue by dpb587-pivotal** [cloudfoundry-incubator/bosh-vsphere-cpi-release#141]
I was noticing that when configuring vSphere, it's easy to confuse the configuration of the vCenter endpoint and I'm wondering if we can simplify it. When configuring via CPI config, users are supposed to use `host`, but when configuring with deployment manifests they're supposed to use `address` (which then, [internally](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/ee3104138401315edaf7410b337dc8b3941b9c43/jobs/vsphere_cpi/templates/cpi.json.erb#L9), gets converted to `host`).

I think there may be a few other differences between those configuration methods, but that one seems most notable right night. Mid-term, if possible, it might be nice to try and unify how the CPI is configured between the job properties and CPI config. In theory, the release job might be able to support both `address`/`host`, requiring one to be set, as a migration path.

So far, I've only seen it in the mention linked below; but I suspect people may start noticing this more as CPI config becomes more widely adopted.

Anyways, wanted to raise the concern and see if you had any thoughts or ideas about it. Thanks!

---

 * https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/136#issuecomment-415120787 - original mention
 * https://github.com/cloudfoundry/docs-bosh/pull/564#issuecomment-415207251 - my own confusion attempting to correct docs

**Comment by nehagjain15** [comment]
Tracker Story https://www.pivotaltracker.com/story/show/160008312

**Comment by EleanorRigby** [comment]
#143

**Comment by EleanorRigby** [comment]
#143
