### ISSUE TITLE
Missing creds from vSphere admin account

### ISSUE THREAD

**Issue by forddonald** [cloudfoundry-incubator/bosh-vsphere-cpi-release#15]
I just tested the permissions roster listed in the docs file perm-by-perm for making an administrative user in vCenter and found there are eight missing permissions required when building PCF v1.8 with vSphere 6.0.

Those are:

Virtual Machine: Inventory: Register
Virtual Machine: Inventory: Unregister
Virtual Machine: Interact: Console Interaction
Virtual Machine: Interact: Guest Control with VIX
Virtual Machine: Interact: Defragment All Disks
Virtual Machine: Guest Operations: Query
Virtual Machine: Guest Operations: Modify
Virtual Machine: Guest Operations: Execute

![pcf admin role virtual machine guest ops and interaction](https://cloud.githubusercontent.com/assets/8728723/20806435/843ba350-b7c0-11e6-9c7f-44f25a4cbb5c.png)
![pcf admin role virtual machine config](https://cloud.githubusercontent.com/assets/8728723/20806336/236a18e0-b7c0-11e6-9ae2-c095bb16e9ba.png)

**Comment by forddonald** [comment]
![pcf admin role virtual machine inventory and provisioning](https://cloud.githubusercontent.com/assets/8728723/20806497/c3a7d46e-b7c0-11e6-80a5-7f80ec86e9f4.png)

**Comment by ljfranklin** [comment]
@forddonald Thanks, this is good stuff. Did you see errors from the CPI during a BOSH deployment (debug output) or was the error from the OpsMgr UI (pop-up dialogue)? That will guide us whether we need to update our (CPI's) docs or work with the commercial team to update the commercial docs. That doc is the set of required permissions for a pure BOSH deployment while some additional permissions may or may not be required for commercial installations.

**Comment by forddonald** [comment]
The error reported during the Ops Mgr Apply Changes validation stage. Here's a screenshot of what I saw.
![pcf vsphere missing creds](https://cloud.githubusercontent.com/assets/8728723/20839087/d3698f5e-b870-11e6-93cd-8ef4fad5fb89.png)

**Comment by ljfranklin** [comment]
@forddonald OpsMgr tries to perform some validation to fail quickly, but in this case I think it's checking for permissions that aren't actually required. Could you add a +1 on this story for OpsMgr: https://www.pivotaltracker.com/story/show/129641855? I'm going to close this out as it's an issue with a commercial offering rather than this open source project, but ping me on that Tracker story if you'd like more info.
