### ISSUE TITLE
Disk Snapshot Implementation

### ISSUE THREAD

**Issue by allomov** [cloudfoundry-incubator/bosh-vsphere-cpi-release#16]
Hey, all.

Originally, with BOSH you can snapshot jobs disk with the following command: `bosh [OPTIONS] take-snapshot [INSTANCE-GROUP/INSTANCE-ID]`.

In order to have such functionality, the CPI should implement [snapshot_disk](https://github.com/cloudfoundry/bosh/blob/master/src/bosh_cpi/lib/cloud.rb#L182-L188) method.

I am wondering if there a specific concerns behind the fact the vSphere CPI does not have this method implemented? 

Thank you,
Alex L.

**Comment by ljfranklin** [comment]
Hey @allomov! I'm not super familiar with vSphere snapshots so please correct me if something looks off. My understanding was that a vSphere "snapshot" is used to store the state of a VM (e.g. memory contents) to allow you to reset the entire machine to a previous state. The BOSH concept of a snapshot is about storing a "backup" of a single disk. The vSphere snapshots deal with persistent data in a weird way, where by default the data is written to a redo log until you take a snapshot, at which point the data is actually written to the underlying disk. More info [here](https://www.vmware.com/support/ws4/doc/preserve_snapshot_ws.html#1012273). We disable this redo log in the CPI so all writes go to the underlying disk immediately, so your persistent disks are not covered at all by vSphere snapshots.

Given all that, is there a vSphere-native way to take a disk snapshot? Copying the underlying .vmdk file seems the closest that comes to mind, but that feels a bit strange. Did you have something in mind?

**Comment by allomov** [comment]
Actually I only have a request to create snapshots for VMs created by BOSH. I'll discuss this issue with vShpere operators and will return to it later. Thank you for the answer.

**Comment by cppforlife** [comment]
@allomov feel free to reopen if necessary.
