### ISSUE TITLE
Support configuring vsphere memory ballooning settings

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/bosh-vsphere-cpi-release#17]
We recently ran into an issue where our bosh deployed VMs were having their memory ballooned away causing issues for our deployment.

It would be nice if it were possible to configure on a per vm_type basis the `sched.mem.maxmemctl` parameter.  This would allow us to ensure bosh deployed vms that are sensitive to memory ballooning don't have only an appropriate amount of memory ballooned away from it.

Here are some links talking about ballooning and how to disable/configure it.

https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1002586

https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003586

**Comment by cppforlife** [comment]
makes sense. any other related config that might be useful while we are there?

**Comment by youngm** [comment]
@cppforlife I did some googling and it appears these parameters are mostly undocumented voodoo[1].

Here is a site with a number of the parameters available [2].

It appears that, for the most part, these parameters are one off key value config that vmware exposes whenever they need a workaround for something.  What would you think of the cpi exposing a way to set these parameters generically.  That way next time we run into an issue similar to this we won't have to add another one off feature to the CPI?

[1] https://communities.vmware.com/thread/85890?start=0&tstart=0
[2] http://sanbarrow.com/vmx.html

**Comment by youngm** [comment]
BTW to help save some leg work it appears this is the API used to set these vmx parameters: https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.ConfigSpec.html#extraConfig

**Comment by youngm** [comment]
@amhuber I don't have a strong preference.  That probably sound like the better place to set it.  It would be nice to be able to set parameters for situations like https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/18 also.  But, that property sounds better and more explicit for this case.  Thanks.

**Comment by amhuber** [comment]
It looks like the VMX option for the other setting is:

sched.mem.pin = "TRUE"

That being the case, I agree that just being able to specify arbitrary VMX parameters would be the best option as then we can choose what we want.

Any timeline for adding this?

**Comment by cppforlife** [comment]
@youngm @amhuber we are right now changing some of the vsphere cpi internals, so we can try throwing this in as well: https://www.pivotaltracker.com/story/show/148036961

**Comment by cdutra** [comment]
The list of available vmx options: https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.resmgmt.doc/GUID-F8C7EF4D-D023-4F54-A2AB-8CF840C10939.html

**Comment by cppforlife** [comment]
Support added in v42: https://github.com/cloudfoundry/docs-bosh/commit/648c969b92da38ecaa3925369271e923a5015b97
