### ISSUE TITLE
Need to handle opaque network backing for virtual nic

### ISSUE THREAD

**Issue by danting1** [cloudfoundry-incubator/bosh-vsphere-cpi-release#19]
As VMware vSphere 6.5 supports opaque network, please help add vitrual nic backing for opaque network attachment when creating virtual nic.

https://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.vspsdk.apiref.doc/vim.vm.device.VirtualDevice.BackingInfo.html
https://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.vspsdk.apiref.doc/vim.vm.device.VirtualEthernetCard.OpaqueNetworkBackingInfo.html

**Comment by cppforlife** [comment]
Salvatore (VMware) recently mentioned that there is an incoming PR for this feature.

**Comment by cppforlife** [comment]
Story started: https://www.pivotaltracker.com/story/show/131478755

**Comment by cppforlife** [comment]
Available in v40.
