### ISSUE TITLE
Host anti-affinity for instances in the same instance group and AZ (cluster/resource pool)

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/bosh-vsphere-cpi-release#21]
I understand that if I have an `instance_group` with several `azs`, BOSH will try to balance instances across AZs to provide AZ-level anti-affinity.  For the VMs that will be scheduled within the same AZ (which, on vSphere, corresponds to a cluster and optional resource pool), are there any guarantees around host-level anti-affinity?  Or, is there some option that could be passed to the CPI to request that it schedules in an anti-affine manner?

/cc @cppforlife @zaksoup

**Comment by cppforlife** [comment]
seems like as we confirmed there is no way to do so from vsphere perspective without setting a "hard" hint. closing.
