### ISSUE TITLE
CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Invalid configuration for device '11'

### ISSUE THREAD

**Issue by ronakbanka** [cloudfoundry-incubator/bosh-vsphere-cpi-release#22]
Recently we've been experiencing this issue with both bosh-init & bosh deploy with vsphere cpi where vm creating is failing during clone phase of cpi call.

Tried with multiple cpi versions , below debug logs are from `cpi v38`

`For bosh-init`
When deploying for the first time there are no issues, but when deploying again with some change in deployment manifest , bosh-init fails with device error.

If stemcell block is removed from state file and bosh-init deploy is fired again , everything goes smoothly, that means `everytime fresh stemcell is uploaded it works`.

While debugging , got this stack trace from bosh-init debug logs

```bash
I, [2017-03-02T03:46:09.504663 #18705]  INFO -- : Cloning vm: (VSphereCloud::Resources::VM (cid="sc-7b961d98-857b-4590-9ff5-8d2c020471e4")) to vm-78b3a003-3e92-46a5-96be-68579ce27a37
D, [2017-03-02T03:46:09.504803 #18705] DEBUG -- : Running method 'FindByInventoryPath'...
D, [2017-03-02T03:46:09.508589 #18705] DEBUG -- : Running method 'RetrieveProperties'...
D, [2017-03-02T03:46:09.513017 #18705] DEBUG -- : Running method 'CloneVM_Task'...
D, [2017-03-02T03:46:09.534150 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:09.539643 #18705] DEBUG -- : Starting task 'VirtualMachine.clone'...
D, [2017-03-02T03:46:09.540111 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:10.546503 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:11.553379 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:12.599832 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:14.184733 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:16.583993 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
D, [2017-03-02T03:46:20.216892 #18705] DEBUG -- : Running method 'RetrievePropertiesEx'...
W, [2017-03-02T03:46:20.225565 #18705]  WARN -- : Error running task 'VirtualMachine.clone'. Failed with message 'Invalid configuration for device '11'.'.
```

```bash
<RetrievePropertiesExResponse xmlns="urn:vim25"><returnval><objects><obj type="Task">task-322042</obj><propSet><name>info.descriptionId</name><val xsi:type="xsd:string">VirtualMachine.clone</val></propSet><propSet><name>info.entity</name><val type="VirtualMachine" xsi:type="ManagedObjectReference">vm-60846</val></propSet><propSet><name>info.error</name><val xsi:type="LocalizedMethodFault"><fault xsi:type="InvalidDeviceSpec"><property>virtualDeviceSpec.device.backing.parent.fileName</property><deviceIndex>11</deviceIndex></fault><localizedMessage>Invalid configuration for device &apos;11&apos;.</localizedMessage></val></propSet><propSet><name>info.name</name><val xsi:type="xsd:string">CloneVM_Task</val></propSet><propSet><name>info.state</name><val xsi:type="TaskInfoState">error</val></propSet></objects></returnval></RetrievePropertiesExResponse>
</soapenv:Body>
</soapenv:Envelope>
Rescued Unknown: Invalid configuration for device '11'.. backtrace: /home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/lib/cloud/vsphere/retryer.rb:13:in `try'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/lib/cloud/vsphere/task_runner.rb:12:in `run'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/lib/cloud/vsphere/vcenter_client.rb:50:in `wait_for_task'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/lib/cloud/vsphere/vm_creator.rb:88:in `create'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:259:in `block in create_vm'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:206:in `create_vm'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-2.0.1/lib/bosh/cpi/cli.rb:71:in `public_send'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-2.0.1/lib/bosh/cpi/cli.rb:71:in `run'
/home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<main>'
[File System] 2017/03/06 09:05:36 DEBUG - Remove all /home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/jobs/vsphere_cpi
[File System] 2017/03/06 09:05:36 DEBUG - Remove all /home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/blobs/5a85bf97-a29c-4bf6-40cc-ca4be17221a5
[File System] 2017/03/06 09:05:36 DEBUG - Remove all /home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/tmp/stemcell-manager347632596
[File System] 2017/03/06 09:05:36 DEBUG - Remove all /home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/tmp/bosh-init-release065385170
[File System] 2017/03/06 09:05:36 DEBUG - Remove all /home/.bosh_init/installations/fde44370-8f88-45df-7524-6d792d706eb1/tmp/bosh-init-release627218441
[main] 2017/03/06 09:05:36 ERROR - Command 'deploy' failed: Deploying: Creating instance 'bosh/0': Creating VM: Creating vm with stemcell cid 'sc-7b961d98-857b-4590-9ff5-8d2c020471e4': CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Invalid configuration for device '11'.","ok_to_retry":false}
```

mentioning `<fault xsi:type="InvalidDeviceSpec"><property>virtualDeviceSpec.device.backing.parent.fileName</property><deviceIndex>11</deviceIndex>` as invalid device spec

Going through few vmware docs , got the reference about the property being used when `Performing Advanced Manipulation of Delta Disks` in case of `linked clones`.

References:
[Vmware linked clone notes](https://www.vmware.com/support/developer/vc-sdk/linked_vms_note.pdf)
[Vmware spec](https://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.device.VirtualDisk.FlatVer2BackingInfo.html) - parent property is described here in detail which is used during clone phase
[CPI code for backing spec](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/5ea37ac72ee6da4b2e260af8590cd78326e02374/src/vsphere_cpi/lib/cloud/vsphere/resources/ephemeral_disk.rb#L38) - As of now parent property is not added here in spec , as optional

__Observed another thing which is probably cause of above issue__

- When updating vm with bosh-init , during delete phase , `.vmdk file from base stemcell directory is also deleted` , which shouldn't be the case because same vmdk should be used next time during vm creation phase.

`Contents of stemcell dir on datastore after first Bosh-init deploy` 
<img width="426" alt="screen shot 2017-03-07 at 7 12 53 pm" src="https://cloud.githubusercontent.com/assets/2391105/23657657/87382ca0-0382-11e7-8ee7-ea1785591806.png">

`Contents of stemcell dir on datastore after manifest update & Bosh-init deploy` 

```bash
Started deploying
  Waiting for the agent on VM 'vm-7cf258dd-85d8-4a6c-8267-fa75a07b4ddf'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:01)
  Unmounting disk 'disk-e8ebd8de-da10-4feb-ad9b-180efa333662'... Finished (00:00:01)
  Deleting VM 'vm-7cf258dd-85d8-4a6c-8267-fa75a07b4ddf'... Finished (00:01:01)
  Creating VM for instance 'bosh/0' from stemcell 'sc-4c722f61-e085-4bea-a377-4ab6518818fd'... Failed (00:02:16)
Failed deploying (00:03:23)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Creating VM:
        Creating vm with stemcell cid 'sc-4c722f61-e085-4bea-a377-4ab6518818fd':
          CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Invalid configuration for device '11'.","ok_to_retry":false}
```
<img width="666" alt="screen shot 2017-03-07 at 10 06 27 pm" src="https://cloud.githubusercontent.com/assets/2391105/23657658/8738e10e-0382-11e7-81c6-6ab6a58a5740.png">

**Comment by ronakbanka** [comment]
@cdutra can you take a look at this?

**Comment by cppforlife** [comment]
@ronakbanka did you figure out if something is killing disks from iaas side?

**Comment by ronakbanka** [comment]
@cppforlife didn't find any such thing which is killing disks , but this started happening after our IaaS upgraded from 5.5 to 6.

**Comment by cppforlife** [comment]
@ronakbanka how frequently does this happen? almost immediately and consistently? we run lifecycle tests against vsphere 6.0 env which seems to spin up multiple vms per stemcells.

**Comment by zaksoup** [comment]
Lifecycle specs run the following tags: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/e51dcb3d77f28397a7529991228e166acab650e5/ci/pipeline.yml#L64

In the Spec Helper for integration tests we upload a stemcell once: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/e51dcb3d77f28397a7529991228e166acab650e5/src/vsphere_cpi/spec/integration/spec_helper.rb#L17-L21

All `create_vm` calls from the CPI will use that stemcell for the rest of the Rspec run. This should exercise creating multiple VMs from a single stemcell image.

**Comment by CAFxX** [comment]
@cppforlife this happens very frequently in our setup. Do you guys test against multiple clusters?

**Comment by ronakbanka** [comment]
@zaksoup Issue is not during create_vm stage but when a vm is being deleted , vsphere is deleting the .vmdk from base stemcell datastore dir , so next time during create_vm stage it fails as no base virtual disk.

We are experiencing this in vsphere 6 env but not in vsphere 5.5 .

**Comment by cppforlife** [comment]
@ronakbanka @CAFxX just created a story to try this manually: https://www.pivotaltracker.com/story/show/143189927.

**Comment by CAFxX** [comment]
@cppforlife maybe underline in the story that this happens with create-**delete**-create cycle (see screenshots and repro instructions in https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/22#issue-212330458)

**Comment by zaksoup** [comment]
Hey @ronakbanka @CAFxX @liuweichu, I am working with @cunnie to reproduce your issue but we're having trouble. Can you please provide us with a copy of your (redacted) manifest and cloud-config?

Here's what we've done so far:

1. Deploy a bosh director using the latest `bosh2` CLI to a vSphere 6.0 with [this manifest](https://gist.github.com/zaksoup/b641c4fb581ef5dfd5ba0a48d482ae0c) (generated via [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment))
1. set the following cloud-config
    ```
    azs:
    - name: z1
      cloud_properties:
        datacenters:
        - clusters: [scarlet-1: {}]

    vm_types:
    - name: default
      az: z1
      cloud_properties:
        cpu: 2
        ram: 1024
        disk: 3240

    disk_types:
    - name: default
      disk_size: 3000

    networks:
    - name: default
      type: manual
      subnets:
      - range: 10.xx.yy.0/24
        gateway: 10.xx.yy.1
        reserved: [10.xx.yy.2-10.xx.yy.249]
        az: z1
        dns: [8.8.8.8]
        cloud_properties:
          name: scarlet

    compilation:
      workers: 5
      reuse_compilation_vms: true
      az: z1
      vm_type: default
      network: default
    ```
1. Upload the latest vSphere Ubuntu Stemcell
1. Deploy the following manifest
    ```yaml
    ---
    name: repro-issue

    releases: []

    stemcells:
    - alias: ubuntu
      os: ubuntu-trusty
      version: latest

    instance_groups:
    - name: dummy
      azs: [z1]
      instances: 2
      vm_type: default
      persistent_disk_type: default
      stemcell: ubuntu
      networks:
      - name: default
        default:
        - dns
        - gateway
    # - name: transformers
      jobs: []

    update:
      canaries: 1
      max_in_flight: 6
      serial: false
      canary_watch_time: 1000-60000
      update_watch_time: 1000-60000
    ```
1. Delete the deployment
1. Redeploy.

We were hoping that deleting the deployment and redeploying would exercise the create delete recreate cycle but we see the second deployment complete successfully. 

Here is what the stemcell looks like in our vSphere: <img width="520" alt="screen shot 2017-03-27 at 2 24 07 pm" src="https://cloud.githubusercontent.com/assets/296065/24775602/735d4550-1ad2-11e7-862b-4bb3c63ca5bd.png">

Thanks!
Zak + Brian

**Comment by ronakbanka** [comment]
@zaksoup @cunnie I am using bosh create-env with init configuration , issue is still there ,but i noticed one spec difference when asked out IaaS guys to give hostd logs from 2 vsphere env.

There is a difference in `deviceChange.backing.parent` , in vsphere 5.5 it is null where as in in vsphere 6 it points to stemcell vmdk , and the vmdk delete is occurring in vsphere 6 where this property is set in config.

one below is from vsphere 5.5 
```bash
2017-04-05T06:58:39.746Z [3ED40B70 verbose 'Vcsvc.LLPM' opID=276a9a3b-16 user=vpxuser] LLPM reconfig (vim.vm.ConfigSpec) {
-->    dynamicType = <unset>,
-->    changeVersion = <unset>,
-->    name = <unset>,
-->    version = <unset>,
-->    uuid = <unset>,
-->    instanceUuid = <unset>,
-->    npivWorldWideNameType = <unset>,
-->    npivDesiredNodeWwns = <unset>,
-->    npivDesiredPortWwns = <unset>,
-->    npivTemporaryDisabled = <unset>,
-->    npivOnNonRdmDisks = <unset>,
-->    npivWorldWideNameOp = <unset>,
-->    locationId = <unset>,
-->    guestId = <unset>,
-->    alternateGuestName = <unset>,
-->    annotation = <unset>,
-->    files = (vim.vm.FileInfo) {
-->       dynamicType = <unset>,
-->       vmPathName = "[]/vmfs/volumes/53e466e2-887e4d38-b813-6c3be5b6d3f0/vm-2e860675-de64-4607-935a-d92022c1455c/vm-2e860675-de64-4607-935a-d92022c1455c.vmx",
-->       snapshotDirectory = <unset>,
-->       suspendDirectory = <unset>,
-->       logDirectory = <unset>,
-->       ftMetadataDirectory = <unset>,
-->    },
-->    tools = (vim.vm.ToolsConfigInfo) null,
-->    flags = (vim.vm.FlagInfo) null,
-->    consolePreferences = (vim.vm.ConsolePreferences) null,
-->    powerOpInfo = (vim.vm.DefaultPowerOpInfo) null,
-->    numCPUs = <unset>,
-->    numCoresPerSocket = <unset>,
-->    memoryMB = <unset>,
-->    memoryHotAddEnabled = <unset>,
-->    cpuHotAddEnabled = <unset>,
-->    cpuHotRemoveEnabled = <unset>,
-->    virtualICH7MPresent = <unset>,
-->    virtualSMCPresent = <unset>,
-->    deviceChange = (vim.vm.device.VirtualDeviceSpec) [
-->       (vim.vm.device.VirtualDeviceSpec) {
-->          dynamicType = <unset>,
-->          operation = "remove",
-->          fileOperation = "destroy",
-->          device = (vim.vm.device.VirtualDisk) {
-->             dynamicType = <unset>,
-->             key = 2000,
-->             deviceInfo = (vim.Description) {
-->                dynamicType = <unset>,
-->                label = "Hard disk 1",
-->                summary = "3,145,728 KB",
-->             },
-->             backing = (vim.vm.device.VirtualDisk.FlatVer2BackingInfo) {
-->                dynamicType = <unset>,
-->                fileName = "[]/vmfs/volumes/53e466e2-887e4d38-b813-6c3be5b6d3f0/vm-2e860675-de64-4607-935a-d92022c1455c/vm-2e860675-de64-4607-935a-d92022c1455c_1.vmdk",
-->                datastore = 'vim.Datastore:datastore-11786',
-->                backingObjectId = "111-2000-0",
-->                diskMode = "persistent",
-->                split = false,
-->                writeThrough = false,
-->                thinProvisioned = false,
-->                eagerlyScrub = <unset>,
-->                uuid = "6000C294-5167-070d-b38d-bfa7cadbb5e2",
-->                contentId = "166b589dceb61a8900586e0dd12f5239",
-->                changeId = <unset>,
-->                parent = (vim.vm.device.VirtualDisk.FlatVer2BackingInfo) null,
-->                deltaDiskFormat = "redoLogFormat",
-->                digestEnabled = false,
-->                deltaGrainSize = <unset>,
-->             },
-->             connectable = (vim.vm.device.VirtualDevice.ConnectInfo) null,
-->             slotInfo = (vim.vm.device.VirtualDevice.BusSlotInfo) null,
-->             controllerKey = 1000,
-->             unitNumber = 0,
-->             capacityInKB = 3145728,
-->             capacityInBytes = 3221225472,
-->             shares = (vim.SharesInfo) {
-->                dynamicType = <unset>,
-->                shares = 1000,
-->                level = "normal",
-->             },
-->             storageIOAllocation = (vim.StorageResourceManager.IOAllocationInfo) {
-->                dynamicType = <unset>,
-->                limit = 500,
-->                shares = (vim.SharesInfo) {
-->                   dynamicType = <unset>,
-->                   shares = 1000,
-->                   level = "normal",
-->                },
-->                reservation = 0,
-->             },
-->             diskObjectId = "111-2000",
-->             vFlashCacheConfigInfo = (vim.vm.device.VirtualDisk.VFlashCacheConfigInfo) null,
-->          },
-->       },
```

One from vsphere 6 is 

```bash
2017-03-10T07:16:21.716Z [2BF80B70 verbose 'Vcsvc.LLPM' opID=4155057b-bd user=vpxuser:VSPHERE.LOCAL\rpaas] LLPM reconfig (vim.vm.ConfigSpec) {
-->    dynamicType = <unset>,
-->    changeVersion = <unset>,
-->    name = <unset>,
-->    version = <unset>,
-->    uuid = <unset>,
-->    instanceUuid = <unset>,
-->    npivWorldWideNameType = <unset>,
-->    npivDesiredNodeWwns = <unset>,
-->    npivDesiredPortWwns = <unset>,
-->    npivTemporaryDisabled = <unset>,
-->    npivOnNonRdmDisks = <unset>,
-->    npivWorldWideNameOp = <unset>,
-->    locationId = <unset>,
-->    guestId = <unset>,
-->    alternateGuestName = <unset>,
-->    annotation = <unset>,
-->    files = (vim.vm.FileInfo) {
-->       dynamicType = <unset>,
-->       vmPathName = "[]/vmfs/volumes/5507b83b-7346c089-d2ed-0090fa8aa610/vm-12344265-b3ee-4eb9-923c-8a455d975240/vm-12344265-b3ee-4eb9-923c-8a455d975240.vmx",
-->       snapshotDirectory = <unset>,
-->       suspendDirectory = <unset>,
-->       logDirectory = <unset>,
-->       ftMetadataDirectory = <unset>,
-->    },
-->    tools = (vim.vm.ToolsConfigInfo) null,
-->    flags = (vim.vm.FlagInfo) null,
-->    consolePreferences = (vim.vm.ConsolePreferences) null,
-->    powerOpInfo = (vim.vm.DefaultPowerOpInfo) null,
-->    numCPUs = <unset>,
-->    numCoresPerSocket = <unset>,
-->    memoryMB = <unset>,
-->    memoryHotAddEnabled = <unset>,
-->    cpuHotAddEnabled = <unset>,
-->    cpuHotRemoveEnabled = <unset>,
-->    virtualICH7MPresent = <unset>,
-->    virtualSMCPresent = <unset>,
-->    deviceChange = (vim.vm.device.VirtualDeviceSpec) [
-->       (vim.vm.device.VirtualDeviceSpec) {
-->          dynamicType = <unset>,
-->          operation = "remove",
-->          fileOperation = "destroy",
-->          device = (vim.vm.device.VirtualDisk) {
-->             dynamicType = <unset>,
-->             key = 2000,
-->             deviceInfo = (vim.Description) {
-->                dynamicType = <unset>,
-->                label = "Hard disk 1",
-->                summary = "3,145,728 KB",
-->             },
-->             backing = (vim.vm.device.VirtualDisk.FlatVer2BackingInfo) {
-->                dynamicType = <unset>,
-->                fileName = "[]/vmfs/volumes/5507b83b-7346c089-d2ed-0090fa8aa610/vm-12344265-b3ee-4eb9-923c-8a455d975240/vm-12344265-b3ee-4eb9-923c-8a455d975240.vmdk",
-->                datastore = 'vim.Datastore:datastore-1211',
-->                backingObjectId = "725-2000-0",
-->                diskMode = "persistent",
-->                split = false,
-->                writeThrough = false,
-->                thinProvisioned = false,
-->                eagerlyScrub = <unset>,
-->                uuid = "6000C29b-233c-e226-9381-34bf9fc78093",
-->                contentId = "b0e8b00c8d1601f4a87255eba20e04db",
-->                changeId = <unset>,
-->                parent = (vim.vm.device.VirtualDisk.FlatVer2BackingInfo) {
-->                   dynamicType = <unset>,
-->                   fileName = "[]/vmfs/volumes/5507b83b-7346c089-d2ed-0090fa8aa610/sc-af1c2748-6463-4cc7-8696-ddcb53b2270c/sc-af1c2748-6463-4cc7-8696-ddcb53b2270c.vmdk",
-->                   datastore = 'vim.Datastore:datastore-1211',
-->                   backingObjectId = "725-2000-1",
-->                   diskMode = "persistent",
-->                   split = <unset>,
-->                   writeThrough = <unset>,
-->                   thinProvisioned = false,
-->                   eagerlyScrub = <unset>,
-->                   uuid = "6000C29b-233c-e226-9381-34bf9fc78093",
-->                   contentId = "b0e8b00c8d1601f4a87255eba20e04db",
-->                   changeId = <unset>,
-->                   parent = (vim.vm.device.VirtualDisk.FlatVer2BackingInfo) null,
-->                   deltaDiskFormat = <unset>,
-->                   digestEnabled = <unset>,
-->                   deltaGrainSize = <unset>,
-->                },
-->                deltaDiskFormat = "redoLogFormat",
-->                digestEnabled = false,
-->                deltaGrainSize = <unset>,
-->             },
-->             connectable = (vim.vm.device.VirtualDevice.ConnectInfo) null,
-->             slotInfo = (vim.vm.device.VirtualDevice.BusSlotInfo) null,
-->             controllerKey = 1000,
-->             unitNumber = 0,
-->             capacityInKB = 3145728,
-->             capacityInBytes = 3221225472,
-->             shares = (vim.SharesInfo) {
-->                dynamicType = <unset>,
-->                shares = 1000,
-->                level = "normal",
-->             },
-->             storageIOAllocation = (vim.StorageResourceManager.IOAllocationInfo) {
-->                dynamicType = <unset>,
-->                limit = -1,
-->                shares = (vim.SharesInfo) {
-->                   dynamicType = <unset>,
-->                   shares = 1000,
-->                   level = "normal",
-->                },
-->                reservation = 0,
-->             },
-->             diskObjectId = "725-2000",
-->             vFlashCacheConfigInfo = (vim.vm.device.VirtualDisk.VFlashCacheConfigInfo) null,
-->          },
-->       },
```

**Comment by cunnie** [comment]
@ronakbanka Thank you for the hostd output.

Could you please provide the bash steps you ran and a redacted manifest, state.json file, and cloud-config? Are you doing a `bosh create-env` followed by a `bosh delete-env` and the problem appears when you run `bosh create-env` again? Or do you deploy a director with `bosh create-env` and then do a `bosh deploy` followed by a `bosh delete-deployment` and then with a `bosh deploy` again?

We are unable to reproduce your problem. If you could provide an example set of manifests and an example bash script to demonstrate that would be incredibly useful. Very explicit and specific steps to reproduce will be helpful. 

This problem is interesting and we want to make sure we help you out and fix any bugs that might be causing this quickly.

Best @cunnie and @zaksoup

**Comment by zaksoup** [comment]
@ronakbanka Hey, we're still very interested in understanding what's causing your problem! Can you please provide the bash steps you ran and a redacted manifest, state.json file, and cloud-config? 

Thanks!
@cunnie and @zaksoup

**Comment by ronakbanka** [comment]
@zaksoup @cunnie We just moved to a new cluster with same version 6 and now we are not experiencing this strange issue . There was some db issues on our previous cluster , was not able to find if it was related to stemcell issue in a way. 

can close this now and will see it it happens again.

**Comment by cunnie** [comment]
@ronakbanka sounds good. please re-open this issue if you can reproduce it!

@zaksoup && @cunnie

**Comment by nitinpadalia** [comment]
Hi We're experiencing similar problem after we upgraded to vSphere 6.0 from vSphere 5.5, however we're not creating new environment. We're just scaling down some Diego VMs. If we scale up then there is no issue, however when we scale down it throws error:
 Unknown CPI error 'Unknown' with message 'Invalid configuration for device '0'.' in 'delete_vm' CPI method.
Further retries of deploy attempts fail as well. 
One workaround we could find is delete the VM via BOSH CCK then deploy again.

Following is the last SOAP Request/Response in the task logs:
= Request\n\nPOST /sdk/vimService HTTP/1.1\r\nSOAPAction: \"urn:vim25/5.1\"\r\nAccept-Encoding: gzip, deflate\r\nContent-Type: text/xml; charset=UTF-8\r\nCookie: vmware_soap_session=ca6r4ac1a908638470229bc37ca4a4d59fc055ca\r\nUser-Agent: HTTPClient/1.0 (2.7.1, ruby 2.2.4 (2015-12-16))\r\nAccept: */*\r\nDate: Fri, 17 Nov 2017 09:16:49 GMT\r\nContent-Length: 726\r\nHost: vSphereHost\r\n\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soapenv:Envelope xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n<soapenv:Body><RetrievePropertiesEx xmlns=\"urn:vim25\"><_this type=\"PropertyCollector\">propertyCollector</_this><specSet><propSet><type>Task</type><all>false</all><pathSet>info.progress</pathSet><pathSet>info.state</pathSet><pathSet>info.result</pathSet><pathSet>info.error</pathSet></propSet><objectSet><obj type=\"Task\">task-82346</obj><skip>false</skip></objectSet></specSet><options></options></RetrievePropertiesEx></soapenv:Body>\n</soapenv:Envelope>

\n\n= Response\n\nHTTP/1.1 200 OK\r\nDate: Fri, 17 Nov 2017 09:16:49 GMT\r\nCache-Control: no-cache\r\nConnection: Keep-Alive\r\nContent-Type: text/xml; charset=utf-8\r\nX-Frame-Options: DENY\r\nContent-Length: 853\r\n\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soapenv:Envelope xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\"\n xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\n xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"\n xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n<soapenv:Body>\n<RetrievePropertiesExResponse xmlns=\"urn:vim25\"><returnval><objects><obj type=\"Task\">task-82346</obj><propSet><name>info.error</name><val xsi:type=\"LocalizedMethodFault\"><fault xsi:type=\"InvalidDeviceSpec\"><property>virtualDeviceSpec.operation</property><deviceIndex>0</deviceIndex></fault><localizedMessage>Invalid configuration for device &apos;0&apos;.</localizedMessage></val></propSet><propSet><name>info.state</name><val xsi:type=\"TaskInfoState\">error</val></propSet></objects></returnval></RetrievePropertiesExResponse>\n</soapenv:Body>\n</soapenv:Envelope>

**Comment by cunnie** [comment]
This may be related to user permissions (i.e. logging in *not* as `administrator@vsphere.local`).

**Comment by EleanorRigby** [comment]
@cunnie : Did you come across this issue recently? Which vCenter and which CPI version?

**Comment by cunnie** [comment]
@EleanorRigby — I haven't run across this issue in 2 years.
