### ISSUE TITLE
Deploying multiple CFs to one NSX breaks security groups

### ISSUE THREAD

**Issue by sambryant4** [cloudfoundry-incubator/bosh-vsphere-cpi-release#28]
Currently security groups are automatically created for all instance groups in a deployment when NSX is enabled. In fact you actually get one security group namespaced to the deployment and one namespaced just to the instance group. As such two deployments can very easily step on each other.

As a minimum a security_group prefix could be defined to ensure jobs get namespaced appropriately.

**Comment by cppforlife** [comment]
closing this issue, but keeping pr for discussion (since there are more comments there).
