### ISSUE TITLE
CPI tries to connect to ESX hosts - is there any other way?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry-incubator/bosh-vsphere-cpi-release#30]
We're trying to deploy a bosh director to our VSphere/ESX cluster; however, it fails when uploading the stemcell since it tries to connect to ESX hosts:

```
bosh create-env bosh-deployment/bosh.yml \
     --state=state.json \
     --vars-store=creds.yml \
     -o bosh-deployment/vsphere/cpi.yml \
...
     -v vcenter_ip=<IP of VCenter> \
...
```

Error:
```
...
Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3421.4'... Failed (00:00:08)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3421.4):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"Connection refused - Connection refused - connect(2) for \"<hostname of ESX host>\" port 443 (<hostname of ESX host>:443)","ok_to_retry":false}

Exit code 1
```

The [docs](https://bosh.io/docs/vsphere-cpi.html#notes) mention this:

> The vSphere CPI requires access to port 80/443 for all the ESXi hosts in your vSphere resource pool(s). In order to upload stemcells to vSphere, the vSphere CPI makes use of an API call that returns a URL that the CPI should make a `POST` request to in order to upload the stemcell. This URL could have a hostname that resolves to any one of the ESXi hosts that are associated with your vSphere resource pool(s).

We were expecting that the CPI only needs to communicate to the VSphere API to fulfill its task. In our case, communication to the ESX hosts is not possible (they're on a complete different network segment). I'm afraid a lot of big enterprises have a similar setup.

Is there a way to get the CPI running without direct interaction to the ESX hosts?
Any suggestions would be greatly appreciated!

**Comment by MatthiasWinzeler** [comment]
We discussed this with various VMWare experts who confirmed it: Clients that use to the VCenter API do need access to the ESX hosts, too, in order to use all functions - this is by design.

We could solve our problem by configuring the CPI to use a HTTP proxy that has connectivity (and DNS resolution) to VCenter and all ESX hosts; I guess this could help in other enterprise setups, too.

**Comment by cwb124** [comment]
I am running into a slightly related issue here.  I have 4 ESX hosts in my test environment where I'm deploying open source CF.  I have connectivity to 443 on these hosts, but they have untrusted default certs and I think that's hanging up my stemcell upload.

Error:   L Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esxtest-1p.sys.company.net:443)' in 'create_stemcell' CPI method.

Any way for bosh to ignore untrusted certs, just for test/development purposes?

**Comment by MatthiasWinzeler** [comment]
@cwb124 That sounds more like a DNS issue to me. Are you able to resolve the hostname from your bosh/bosh-init, i.e. using `dig` or `nslookup`?

The CPI anyway seems to skip ssl verification for backwards compat: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/v42/src/vsphere_cpi/lib/cloud/vsphere/cpi_http_client.rb#L10

**Comment by cwb124** [comment]
Yeah it was indeed a DNS issue.  I skimmed the bosh.yml when I should have focused more on it.  The public DNS server in the bosh.yml was the culprit. I'm going to create a PR for some of the documentation for Vsphere to check and edit the bosh.yml with internal DNS server.

**Comment by svrc-pivotal** [comment]
Just bumping this one.   We've tested with GOVC and it does not require ESXi connectivity, it does all of its actions including uploading to Datastores through vCenter (verified with tcpdump).   

Is it still accurate that we need ESXi connectivity?

**Comment by EleanorRigby** [comment]
Can you provide the command in govc you used? I traced the command `govc import.ovf` and found out that they use excat same way CPI uses to upload.

**Comment by svrc-pivotal** [comment]
I think I found the culprit in the CPI - it’s the file provider that uploads the ISO CD-ROM image.   It falls back to a vCenter upload though.  Could we maybe flip the logic and make the vCenter upload the default?  Not sure what versions of VC/ESXi would break.

**Comment by EleanorRigby** [comment]
@svrc-pivotal : The fallback to vCenter upload is always certain if upload through host does not complete. Why do you want vCenter upload to be default?

**Comment by MatthiasWinzeler** [comment]
@EleanorRigby In our case, the VCenter and the ESX hosts are in dedicated management networks, far away from the workload where CF lives - and I guess other enterprises have the same issue. So it would be easier if the CPI only talks to only one endpoint, the vcenter - then we can just make this one vcenter endpoint accessible from the workload (for example with a reverse proxy) and don't have to make all ESX hosts accessible from the workload as well (which in most cases also involves needing the management DNS that can resolve the ESX hosts).

**Comment by svrc-pivotal** [comment]
@eleanorrigby ^ what he said.  It’s invariably been a moderate pain to get direct ESX access.

**Comment by EleanorRigby** [comment]
@eamonryan : Can you provide me with some code sample or blog which talks about this improvement?

This is definitely something which I also believe will benefit users and also will help developers to get rid of any operations to do with ESXi hosts. Ideally, I would also like CPI to never get down into host world.

**Comment by eamonryan** [comment]
@EleanorRigby I don't have something to link, I was mainly referencing @svrc-pivotal 's earlier comment that the behaviour using `govc` appears to have changed in some combination of `govc` and some vCenter version.

I looked back over the last couple vCenter release notes and did not see any change mentioned that would indicate that OVF/OVA uploads are now going via vCenter, so it's possible it is not a publically documented change and may have been done to support some other VMware product integration.

Perhaps the vCenter team would know?

**Comment by zopar** [comment]
I would like to contribute to this discussion
Ansible seems to use vcenter for uploading

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py

https://docs.ansible.com/ansible/latest/modules/vmware_deploy_ovf_module.html

I would like also to add that the file_provider.rb in some cases does not rescue correctly for that does not try to use the vcenter for uploading

You have:  rescue FileTransferError
this is generated by get_healthy_host that checks if an host is powered on, that does not means that the host is reachable (for example in case of firewall). So the function fails with an unknown error and the uploading function does not rescue to vcenter upload.

get_healthy_host should manage a connection error in case the host is healthy but not reachable, so you can reascue in this case the upload to vcenter.
Or simply try in any case vcenter in case of any type of error
Or use vcenter upload as default and rescue on esxi
More in general if you use vcenter you do not want to connect to esxi. Other tools like ansible always use vcenter and not esxi for operations like this one.

Hope this helps

**Comment by EleanorRigby** [comment]
@zopar :  I think you are mixing two concepts here 1. uploading ovf  2. uploading agent files

For uploading ovf where you get this error it only uses `upload_file_to_url` in `file_provider.rb` . This method has nothing to do with vCenter rescue.

The above python file in Ansible has https://github.com/ansible/ansible/blob/4732728e40beaff2338d0bdb9c01e9662d59f063/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py#L444

which again uses host url(deviceUrl) in `vcenter lease` to upload and suffers from same ESXi firewalled problem. Does this sound right?

**Comment by zopar** [comment]
You are right my mistake.
So we should use a template but in any case you need to upload the ova the first time with the same technique...
