### ISSUE TITLE
Cluster selection including non specified datastores in calculation instead of only specified ones

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/bosh-vsphere-cpi-release#35]
We have a problem in our environment where VMs appear to be getting placed in clusters we wouldn't expect.

## Our scenario
* We have 2 clusters.
* We have configured bosh to use a single datastore that is shared between the 2 clusters.
## Behavior
* Our VMs are repeatedly picking a single cluster causing that cluster to run hot on memory.
## Expected Behaviour
* Since we use the same datastore for both clusters I'd think that the picker algorithm should pick the cluster will more memory available.

## What I found while digging through the code and debugging
Cluster selection is taking place here: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/7fb6677a6a8dd9d4221dd57c171c9b0932d152fb/src/vsphere_cpi/lib/cloud/vsphere/cluster_picker.rb#L15

Browsing through the code it appears that the method is supposed to be checking:
* placements_with_minimum_disk_migrations
* placements_with_max_free_space
* placements_with_max_free_memory

Debugging through the code it appears we have a problem with Disk Max Free Space calculation.  The main code is: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/027c3f4c8f769806b86fda88375dbee21688a4f0/src/vsphere_cpi/lib/cloud/vsphere/datastore_picker.rb#L21

It appears that the balance_score is including in its calculation all of the accessible datastores on the cluster and not just the datastore(s) that we have selected via `datastore_pattern`.

This causes the cluster picker to always pick the cluster with the most available disk space regardless of the datastores we actually have configured.

What I would expect is that if we use the same datastore for both clusters then the disk selection process of `cluster_picker` would result in a tie for the 2 clusters and would therefore move on to picking based on memory.

Thoughts?

**Comment by cdutra** [comment]
Hi @youngm,

"It appears that the balance_score is including in its calculation all of the accessible datastores on the cluster and not just the datastore(s) that we have selected via datastore_pattern."

Yes, the datastore picker will look in all accessible datastores. However during the VM creation the disk configuration will have the [`ephemeral_datastore_pattern`](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/7fb6677a6a8dd9d4221dd57c171c9b0932d152fb/src/vsphere_cpi/lib/cloud/vsphere/datastore_picker.rb#L49) which will be used by the datastore picker to match the configured datastores among all accessible ones.

This should make the cluster picker choose the cluster with more available memory within the ones configured in `ephemeral_datastore_pattern`.

**Comment by youngm** [comment]
@cdutra Hmm.....however, it appears that the code here: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/7fb6677a6a8dd9d4221dd57c171c9b0932d152fb/src/vsphere_cpi/lib/cloud/vsphere/cluster_picker.rb#L71

Simply picks the datastore with the best score.  And it appears that the score is calculated without regard to the `target_datastore_pattern`, right?

**Comment by cdutra** [comment]
@youngm The score is calculated [here](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/datastore_picker.rb#L21) and the placement [here](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/9e611e35c08e8bdcb0a8d404e20f81e4af179627/src/vsphere_cpi/lib/cloud/vsphere/datastore_picker.rb#L43-L57) and on line [49[(https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/9e611e35c08e8bdcb0a8d404e20f81e4af179627/src/vsphere_cpi/lib/cloud/vsphere/datastore_picker.rb#L49) will filter only if it matches the ones configured in `ephemeral_datastore_pattern`.

The disk configuration are created during [vm creation](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/7fb6677a6a8dd9d4221dd57c171c9b0932d152fb/src/vsphere_cpi/lib/cloud/vsphere/cloud.rb#L229), [here](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/7fb6677a6a8dd9d4221dd57c171c9b0932d152fb/src/vsphere_cpi/lib/cloud/vsphere/disk_configs.rb#L33-L39) and [here](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/7fb6677a6a8dd9d4221dd57c171c9b0932d152fb/src/vsphere_cpi/lib/cloud/vsphere/disk_configs.rb#L59).

**Comment by youngm** [comment]
Thanks @cdutra I'll do some more digging about what is going on and get back with you.

**Comment by cdutra** [comment]
@youngm Thank you! Please, let me know if I can help with anything.

**Comment by youngm** [comment]
@cdutra Here is a test that I believe is illustrating what I'm seeing.  Hopefully it helps you better see what I am attempting to explain because I'm having trouble catching what you are attempting to explain. :)

This test fails with the current code.  I would expect it to pass in order for the cluster picker to move on to checking memory.

```
    describe 'Placement results for single datastore' do
      let(:cluster1_ds) { instance_double(VSphereCloud::Resources::Datastore, free_space: 256) }
      let(:cluster2_ds) { instance_double(VSphereCloud::Resources::Datastore, free_space: 1024) }
      let(:shared_ds) { instance_double(VSphereCloud::Resources::Datastore, free_space: 1024) }
      let(:available_datastores_cluster1) do
       {
         'cluster1-ds' => cluster1_ds,
         'shared-ds' => shared_ds,
       }
      end
      let(:available_datastores_cluster2) do
       {
         'cluster2-ds' => cluster2_ds,
         'shared-ds' => shared_ds,
       }
      end

      let(:az1_disk) do
        instance_double(VSphereCloud::DiskConfig,
          size: 0,
          target_datastore_pattern: 'shared-ds',
          existing_datastore_name: nil
        )
      end
    
      it 'calculates score using picked disk disk only' do
        picker = DatastorePicker.new(0)
        picker.update(available_datastores_cluster1)
        placeholders_cluster1 = picker.best_disk_placement([az1_disk])

         picker = DatastorePicker.new(0)
         picker.update(available_datastores_cluster2)
         placeholders_cluster2 = picker.best_disk_placement([az1_disk])

         expect(placeholders_cluster1[:balance_score]).to eq(placeholders_cluster2[:balance_score])
      end
    end
```

**Comment by cdutra** [comment]
@youngm The datastore picker uses a scoring algorithm which weights its results based on its possible placements therefore the balance score depends on the set of results and not in a particular result itself. In this case when `add_balance_score` is called is called with different inputs (`cluster2_ds` which has more free space) causing the balancing score to be higher.
This makes sense because the cluster2 will indeed have more available space (`cluster2_ds` + `shared_ds`) than cluster1 (`cluster1_ds` + `shared_ds`)

**Comment by cdutra** [comment]
@youngm I believe the case here would be why the free space has higher precedence and excludes possible clusters with similar score but potentially more free memory.
Maybe the best solution would be to have a scoring system that would weight the different criteria (migration, space and memory)?

**Comment by youngm** [comment]
@cdutra Possibly.  For our purposes we are only using the one "targeted" datastore in both clusters.  I don't think we care about the other datastores on the clusters.  There for we assumed that the vsphere cpi wouldn't care about other datastores either all fall through to memory being the deciding factor.

Perhaps you tried to explain this already but can you help me understand why the cpi would want to include non targeted datastores in the score calculation?

**Comment by youngm** [comment]
keep in mind in our environment our CF deployment is only a small tenant of our entire vsphere infrastructure.

**Comment by youngm** [comment]
Perhaps there is a way to only give my CF vsphere user access to its datastore so there are less available datastores?  Maybe that is the correct way for us to tackle this problem.

**Comment by cdutra** [comment]
@youngm The decision of the semantics of `datastore_pattern` was made prior I joined the BOSH CPI team. If I had to guess I believe it was to be more like a soft rule.

**Comment by youngm** [comment]
@cdutra So, the question would it be appropriate to fix this by limiting the score to only targeted datastores?

**Comment by cdutra** [comment]
Possibly

**Comment by youngm** [comment]
I'm going to talk to our vsphere guys see if I can limit what datastores our vsphere user can see and see if that is a possible work around.  I'll report back.

**Comment by youngm** [comment]
I talked to our vsphere guys and it sounds like it wouldn't be trivial to limit our datastore access permissions. So, I think we'd still be looking at a change in the CPI to fix this for us.  Let me know what you dig up regarding the `datastore_pattern` in the score.  If the fix for this is to simply limit the score to datastores in the `datastore_pattern` I may be able to put together a PR for that.

**Comment by cdutra** [comment]
@cppforlife do you have more context in why the `datastore_pattern` isn't a hard rule when deciding what datastores to pick?

**Comment by cdutra** [comment]
@youngm We added a story in our backlog to fix this: https://www.pivotaltracker.com/story/show/151198560

**Comment by youngm** [comment]
@cdutra I noticed this issue was moved to the icebox telling me you may not find time to work on this for a while.

I can create a PR for this.  As a PR I would probably focus on simply fixing the unit test I provided above.  Does that sound like an appropriate fix?

**Comment by cdutra** [comment]
@youngm I'm sorry for the late response. PRs are welcome! We added a story for us to do it because we wanted to do a refactoring on that code.
The PR would really help, though and we appreciate it. Let us know if we can help with anything. You can ping us on slack for questions.

cc @nehagjain15

**Comment by youngm** [comment]
@cdutra Here is a PR a threw together real quick.  If you think the datastore refactor takes some time prioritize merging and releasing this in a reasonable time frame would help my team out.  Thanks.

https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/pull/36

**Comment by cdutra** [comment]
We added in the story. Will chat with @cppforlife to prioritize that. Thanks!

**Comment by youngm** [comment]
It appears my PR has been merged.  Closing this issue.  Thanks!

**Comment by cdutra** [comment]
@youngm Thanks you so much for the PR!
