### ISSUE TITLE
Allow memory reservation -  by default or parameterized

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry-incubator/bosh-vsphere-cpi-release#4]
In src/vsphere_cpi/lib/cloud/vsphere/vm_creator.rb line 46 would look something this:

config_hash = {memory_mb: @memory, num_cpus: @cpu, memory_allocation: VimSdk::Vim::ResourceAllocationInfo.new(reservation: @memory)}

for forced reservation. 

We were short of disk space in our cluster and forcing memory reservation helped us by loosing swap files.

**Comment by cppforlife** [comment]
I'm not sure if we would want to make that a default since it would reserve that memory and will not be able to overcommit afaik. May be a configuration? Are you using this configuration for all VMs you deploy or only for specific ones?

**Comment by ryantang** [comment]
I think this would be a good optional configuration (not the default).  I encourage a a pull request implementing this as an additional configuration under `resource_pools` `cloud_properties` for a `create_vm` call or under `properties` `vsphere` on the vSphere CPI's global config .  I'm closing this issue for now.  Feel free to reopen if needed.
