### ISSUE TITLE
This is not issue 

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-vsphere-cpi-release#43]
Hi thanks for your opensource, is this cpi supports VMware vSphere 6.5, if not please let me know up to  which version of VMware vSphere it supports thanks in advance.

**Comment by cdutra** [comment]
@abhilash07 Yes, the latest vSphere CPI supports vSphere 5.5, 6.0 and 6.5.
You can ask questions in the official bosh-cpi channel here: https://cloudfoundry.slack.com/messages/C094QMKB2
