### ISSUE TITLE
Bump ruby version to 2.4-r3

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry-incubator/bosh-vsphere-cpi-release#44]
As part of [a recent bosh story](https://www.pivotaltracker.com/story/show/153035903) we bumped the ruby version for the director, the ruby bosh-package, and the aws CPI to [2.4-r3](https://github.com/bosh-packages/ruby-release/tree/master/packages/ruby-2.4-r3).  This change should also happen to the bosh-vsphere-cpi-release.  The steps are:

1. Check out the [bosh-packages ruby release](https://github.com/bosh-packages/ruby-release)
2. `cd` into the `bosh-vsphere-cpi-release`
3. With a recent version of the `bosh-cli`, run `bosh vendor-package path/to/bosh-packages/ruby-release ruby-2.4-r3`
4. Change all `ruby-2.4` references in the `bosh-vsphere-cpi-release` to `ruby-2.4-r3`.  Find-and-replace should be good enough.

**Comment by cppforlife** [comment]
also `rm -rf packages/ruby-2.4`

**Comment by nehagjain15** [comment]
Was fixed and released in [v45.1.0](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/releases/tag/v45.1.0))
