### ISSUE TITLE
CPI ignores maintenance mode of datastore

### ISSUE THREAD

**Issue by rerooted** [cloudfoundry-incubator/bosh-vsphere-cpi-release#46]
The datastore accessibility is mentioned in https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/29, but its not quite the same.

We have a range of datastores, at any point in time one or more could be in maintenance mode.  As it stands, the CPI falls over when it tries to create a disk inside a datastore that is in maintenance mode.

Within the ```datastore.rb``` file the object returned by Vim::Datastore + Datastore::PROPERTIES should return a 'summary.maintenanceMode' boolean.  It should be possible to check this value before determining if a datastore can be used.

My Ruby is quite poor, but I would imagine changing https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/resources/datastore.rb#L18

from:
```
ds_properties['summary.accessible'],
```
to:
```
ds_properties['summary.accessible'] &&  ! ds_properties['summary.maintenanceMode'],
```

would cause the datastore to be not selected and the CPI would be free to move to the next datastore for integration.

**Comment by yeshwantbabar** [comment]
Fixed in version 46.
