### ISSUE TITLE
Datacenter  not found

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-vsphere-cpi-release#59]
Hi i am trying to deploy Cloud Foundry on Multi datacenter and configured datastores in datastore-cluster and networks respectively. 
<img width="1306" alt="screen shot 2018-02-06 at 10 27 57 am" src="https://user-images.githubusercontent.com/10971841/35837339-bf8ca0be-0b28-11e8-9e6a-e04178b3d723.png">
<img width="1306" alt="screen shot 2018-02-06 at 10 27 04 am" src="https://user-images.githubusercontent.com/10971841/35837344-c685b50e-0b28-11e8-9f78-05b60fa0ed87.png">
<img width="1301" alt="screen shot 2018-02-06 at 10 27 18 am" src="https://user-images.githubusercontent.com/10971841/35837347-c9f89210-0b28-11e8-8cd6-a974a6c8ed81.png">

But unfortunately i am encountering this error while deploying Micro-Bosh,  

![screen shot 2018-02-06 at 11 54 33 am](https://user-images.githubusercontent.com/10971841/35839592-911393da-0b34-11e8-9d59-dec92d9c7bc3.png)

My Command
<img width="617" alt="screen shot 2018-02-06 at 10 37 19 am" src="https://user-images.githubusercontent.com/10971841/35837489-becc4d04-0b29-11e8-9044-318633667667.png">

Is it possible to deploy Micro-Bosh and CF on Multi-datacenters.

Thanks in advance

**Comment by yeshwantbabar** [comment]
CPI requires access to perf_metrics from vSphere and ESX. Please enable them and give them about 10 mins to populate. 

https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/5ea37ac72ee6da4b2e260af8590cd78326e02374/src/vsphere_cpi/lib/cloud/vsphere/vcenter_client.rb#L260

**Comment by yeshwantbabar** [comment]
Also, vSphere CPI does not support multiple datacenters.

**Comment by abhilash07** [comment]
@yeshwantbabar thanks for your information
