### ISSUE TITLE
No valid placement found for disks

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-vsphere-cpi-release#61]
Hi everyone i am trying to deploy Cloud Foundry on 3 clusters (with single host) in single datacenter and i created datastore cluster for three datastores. More over my vSphere and vCenter Version 6.5 with standard license.
 
![screen shot 2018-02-08 at 10 02 30 am](https://user-images.githubusercontent.com/10971841/35950036-d33b2442-0cb7-11e8-9a2b-cbf91876141e.png)

![screen shot 2018-02-08 at 10 02 44 am](https://user-images.githubusercontent.com/10971841/35950040-d690d876-0cb7-11e8-9e2a-8d5e12364476.png)

My Micro Bosh Command:
<img width="683" alt="screen shot 2018-02-08 at 10 08 46 am" src="https://user-images.githubusercontent.com/10971841/35950101-198658fe-0cb8-11e8-9383-628b71dc4ba6.png">

But i am encountering below error:

<img width="824" alt="screen shot 2018-02-08 at 10 01 24 am" src="https://user-images.githubusercontent.com/10971841/35950116-2abd25da-0cb8-11e8-8191-bd84c3267409.png">

Is there sollution fo this error 

Please refer my cloud-config and cf yaml files
[cf-deployment.txt](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/files/1705370/cf-deployment.txt)
[cloud-config.txt](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/files/1705371/cloud-config.txt)

**Comment by EleanorRigby** [comment]
@abhilash07 : Have you made sure that all the datastores have enough free space?

**Comment by yeshwantbabar** [comment]
Do you have enough free space on the datastores? 

Just a heads up- CPI needs DRS feature in vSphere which comes under enterprise license. So things might fail with a standard license.

**Comment by abhilash07** [comment]
@EleanorRigby  thanks for your quick response, yes all the datastores has 700 GB free space. Moreover i deployed Bosh-Director on datastore1 and i am trying to deploy consul job on datastore 2 and create persistence disk then i am encounter this error 

<img width="824" alt="screen shot 2018-02-08 at 10 01 24 am" src="https://user-images.githubusercontent.com/10971841/35951234-dab0ca28-0cbd-11e8-8f65-91b6ddd3127c.png">

**Comment by abhilash07** [comment]
@yeshwantbabar  yes all the datastores has 700 GB free space. So you mean without DRS enabled it is impossible ???

**Comment by yeshwantbabar** [comment]
Unfortunately, yes. We are planning on supporting DRS disabled mode in the future. But the error that you are seeing here, seems related to disks.

**Comment by abhilash07** [comment]
@EleanorRigby this is my datastores
![screen shot 2018-02-08 at 10 55 47 am](https://user-images.githubusercontent.com/10971841/35951429-b6151da8-0cbe-11e8-87ad-ce1a5a1b2d67.png)
 information

**Comment by yeshwantbabar** [comment]
Is SDRS enabled on these clusters? Can you possibly move them out of the cluster and give it a shot?  

If SDRS is enabled, we can't choose a particular datastore for deployment.

**Comment by abhilash07** [comment]
@yeshwantbabar you're absolutely right, but unfortunately when i deployed CF vms on same micro-bosh datastore it is not getting error. I mean for example first i deployed Bosh-Director on datastore1, Next i started deploying CF VMs on same datastore1 it is successfully creating persistence disk

**Comment by abhilash07** [comment]
@yeshwantbabar yes the SDRS is enabled and DRS is disabled

**Comment by yeshwantbabar** [comment]
Yes, that would not work. We are actually working on supporting SDRS which will be released early next week.

**Comment by abhilash07** [comment]
@yeshwantbabar so you mean if i disable SDRS and DRS on datastore cluster it is possible to overcome above error

**Comment by yeshwantbabar** [comment]
I believe if you disable SDRS on the Datastore cluster and enable DRS on compute cluster, it should work.

**Comment by abhilash07** [comment]
hi everyone is there any solution to deploy CF on multi cluster with multi datastore on vsphere 6.5 standard licence (by disabling DRS and SDRS) . Please refer my yaml files. Thanks in advance 

Micro-Bosh command:

bosh create-env /home/ubuntu/workspace/deployments/bosh-deployment/bosh.yml --state=state.json --vars-store=creds.yml -o /home/ubuntu/workspace/deployments/bosh-deployment/vsphere/cpi.yml -v director_name=vmware-micro-bosh -v internal_cidr=192.168.205.0/24 -v internal_gw=192.168.205.1 -v internal_ip=192.168.205.38 -v network_name="VM Network1" -v vcenter_dc=cloudservice -v vcenter_ds=datastore[1,2,3] -v vcenter_pds=datastore[1,2,3] -v vcenter_ip=192.168.205.20 -v vcenter_user=administrator@vsphere.local -v vcenter_password='$D$32@bhi07-' -v vcenter_templates=bosh-templates -v vcenter_vms=bosh-vms -v vcenter_disks=bosh-disks -v vcenter_cluster=cluster1

Error:

![screen shot 2018-02-09 at 3 31 07 pm](https://user-images.githubusercontent.com/10971841/36014685-65be6d28-0dae-11e8-9c21-1a05a5918d4f.png)

Yaml Files:

[cf.txt](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/files/1709973/cf.txt)
[cloud-config.txt](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/files/1709974/cloud-config.txt)

**Comment by abhilash07** [comment]
Every one thanks for your sugeestions error is solved we can deploy cloud foundry on multi datastores
