### ISSUE TITLE
[feature request] automatically upgrade hw version

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-vsphere-cpi-release#66]
some customers want to run on latest virtual hardware version of a stemcell. it may be to take advantage of perf features, or some to be compatible with new esxi features. recently we had another request for it, so im filing this issue on thier behalf. i think it would be nice to add a feature flag (with a default false) so that we can opt in for some users as a trial run. eventually may be enable for all by default?

we've previously did this experiment to see if we could do it. here is our try: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/commit/346417bb7c0b3b45fcaaf8833fbe9f8c125bc394. story in which we investigated this feature: https://www.pivotaltracker.com/story/show/154215922

**Comment by EleanorRigby** [comment]
#84

**Comment by EleanorRigby** [comment]
Delivered. 
User is required to add a property upgrade_hw_version: true (false by default) to upgrade to the latest version. 
More details : https://www.pivotaltracker.com/story/show/156671737

**Comment by robbo10** [comment]
Hi - is there any update on this story?

https://www.pivotaltracker.com/story/show/156671737

We would like to set this at the global level.

**Comment by EleanorRigby** [comment]
Hi

The story is delivered. Please check
https://bosh.io/docs/vsphere-cpi/#global for the global configuration
option to upgrade the hardware version. And there is a cloud config level
option also available which overrides global config.

Best
Tushar
