### ISSUE TITLE
unknown variable in an error message

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-vsphere-cpi-release#75]
`#{datacenters.inspect}` references to a variable that does not exist.

```
if vm_datacenters.size > 1
  raise "stemcell VM #{vm.inspect} found in multiple datacenters #{datacenters.inspect}"
end
```

https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/v46.1.0/src/vsphere_cpi/lib/cloud/vsphere/cloud.rb#L583-L585

**Comment by nehagjain15** [comment]
This error is not present in latest release, as this method was removed
