### ISSUE TITLE
disk_cid might exceed 255 characters

### ISSUE THREAD

**Issue by Lafunamor** [cloudfoundry-incubator/bosh-vsphere-cpi-release#77]
Hi there

I've found a potential bug when using custom datastore placment for disk-types in my cloud-config.
The result is this error: 
`Error: Unknown CPI error 'InvalidCall' with message 'Arguments are not correct, details: 'invalid base64'' in 'attach_disk' CPI method`

I've trace the problem back to the DB schema definition. When using mysql the column 'disk_cid' is of type varchar(255). Mysql will cut any additional characters after the 255th and thus the result is a loss of data (metadata to be precise).

I see that in the database there is also the column 'cloud_properties_json' which seems to include the same data as the base64 encoded metadata. So I'm not sure if this base64 encoded metadata in the cid field is really needed.

Can you point me to a workaround or is this a thing which can easily be fixed?
Thanks for the help!

Used CPI-release: 45.1.0

**Comment by cppforlife** [comment]
@Lafunamor which version of the director are you using?

**Comment by Lafunamor** [comment]
@cppforlife Sorry, I forgot to add it. It's bosh version 264.6.0

**Comment by ktchen14** [comment]
We need to take a look at the `DirectorDiskCID` here which is where we base64 encode some data into the disk id. @nehagjain15 can we safely remove the additional metadata in the disk id?

**Comment by nehagjain15** [comment]
We can not remove this until we find another way to store and access this information in attach_disk call. Background on why this was added https://www.pivotaltracker.com/n/projects/1133984/stories/114981013

**Comment by Lafunamor** [comment]
Would it be possible to change the type of the 'disk_cid' column to something other than varchar(255)?

**Comment by ktchen14** [comment]
For the record in PostgreSQL there's no performance difference between a `VARCHAR(255)` and a `TEXT` (which has no limit restriction). Both are backed by a `varlena`.

**Comment by cppforlife** [comment]
@Lafunamor closing here, and created above issue in cloudfoundry/bosh
