### ISSUE TITLE
create_vm failure

### ISSUE THREAD

**Issue by alakshman** [cloudfoundry-incubator/bosh-vsphere-cpi-release#81]
Guys

Could someone please help me debug this issue? I keep getting this error on attempt to deploy VMs.

L Error: Unknown CPI error 'Unknown' with message 'Could not transfer file 'https://10.234.36.102/folder/vm-c8fa7d28-67ea-4538-a067-c3c137cd76f7/env.json?dcPath=ppc&dsName=vol-NFScf4', received status code '500'' in 'create_vm' CPI method
Task 162 | 16:42:55 | Creating missing vms: access_z1/02480489-74d1-4605-b53f-41e8e4c8da3c (0) (00:06:32)
Task 162 | 16:42:55 | Error: Unknown CPI error 'Unknown' with message 'Could not transfer file 'https://10.234.36.102/folder/vm-c8fa7d28-67ea-4538-a067-c3c137cd76f7/env.json?dcPath=ppc&dsName=vol-NFScf4', received status code '500'' in 'create_vm' CPI method

**Comment by EleanorRigby** [comment]
This likely means that vcenter is facing some internal error. CPI cannot do anything other than retrying it before giving up. It already does retry 5 times.

**Comment by yeshwantbabar** [comment]
@alakshman  - If you are not facing this issue anymore, would you mind if I close this issue?

**Comment by alakshman** [comment]
Yes please close it.
