### ISSUE TITLE
Free disk space calculation in datastore_picker.rb doesn't take vmware swapfiles into account

### ISSUE THREAD

**Issue by anyandrea** [cloudfoundry-incubator/bosh-vsphere-cpi-release#98]
There is a hardcoded value for the headroom in the datastore_picker.rb that's used when selecting datastores to place a vm/disk. The CPI's choice is based on free space + headroom value but unfortunately it doesn't take into account the fact that vmware creates a temporary swapfile (same size as the vm-RAM is). This might lead to the situation that bosh tries to create this swapfile on a datastore which has not enough free space to do so. You'll see an error message like this:

```
Error: Unknown CPI error 'Unknown' with message 'Failed to extend swap file from 0 KB to XXXX KB
```

We've solved this issue by temporarily changing the headroom value to at least the size of the biggest instance (RAM wise) in the vsphere-cpi code directly on the bosh-director.

Could you please fix this bug by changing the free space calculation for datastores to account for the additional needed vm-RAM size? It would be nice if this is somehow similar handled as it is done for the free disk space calculation by adding the headroom value.

**Comment by anyandrea** [comment]
Any update on this issue?

**Comment by yeshwantbabar** [comment]
Hi @anyandrea  - We have just started working on this one. Will keep you posted. 

Thanks,
Yeshwant

**Comment by anyandrea** [comment]
Hi @yeshwantbabar 
Thank you very much for the update! I'm gonna test it!
Best,
Andrea
